version: '3.8'

services:
  robot-reporting:
    build: .
    container_name: robot-reporting-grafana
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    # Menggunakan restart unless-stopped agar jika VM direstart, robot otomatis menyala
    restart: unless-stopped
